### ISSUE TITLE
Can't use use-bucket command

### ISSUE THREAD

**Issue by AWolf81** [cosmicjs/cosmic-cli#14]
Login command works and returns authenticated. But `use-bucket` returns `Not authorized`.

Do I have to use the read key or is this a problem with Windows? Token & email is stored in `C:\Users\Alexander\.config\configstore\cosmic-cli.json`

Is there a way to get a debug print to get more details why it returns 'Not authorized'?

I'm running Windows 10 Pro (64bit).

Here is a screenshot from my console output from cmd.exe with-in VS code:
![grafik](https://user-images.githubusercontent.com/3046542/39914106-4796c212-5504-11e8-9612-531deae92504.png)

Tested the cli also in a virtual machine with Ubuntu 16.0.4.3 (64bit) with the same log message - so this is not an issue that's only related to Windows.

**Comment by RobinJayaswal** [comment]
@AWolf81 Do you have a read key set on that bucket? If so you need to pass that into the command.

I made a bucket with slug `with-read-key` and set the read-key to be something. Below is the output from use-bucket without and with the read key:

```
$ cosmic use-bucket with-read-key
Not authorized
$ cosmic use-bucket with-read-key --read_key my_personal_key
Now using Bucket with-read-key
```

**Comment by AWolf81** [comment]
@RobinJayaswal Thanks, that's probably the problem. Yes, I'm using a read key.

At the moment, I can't check as my trial ended but I'll check it later. 

I haven't read anything about this. Maybe this should be added to the docs because I thought that I have access after login.
Or adding the feature that a logged-in user has access to the bucket would be great - like a dashboard user also gets full access if the user's role is administrator.

**Comment by AWolf81** [comment]
@RobinJayaswal OK, that was my problem. Now it is working. 

So everything is working - just the documentation wasn't clear to me.
